NumberToTextConversionApplication/NumberToTextConversionApplication/Models/ConvertNumberModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NumberToTextConversionApplication.Models
{
    public class MyDetails
    {
        public string Name { get; set; }
        public double Amount { get; set; }
    }
    public class ConversionResponse
    {
        public string Name { get; set; }
        public string Amount { get; set; }
    }
}

NumberToTextConversionApplication/NumberToTextConversionApplication/Controllers/ConvertController.cs
using NumberToTextConversionApplication.Models;
using System.Net;
using System.Text;
using System.Web.Mvc;

namespace NumberToTextConversionApplication.Controllers
{
	public class ConvertController : Controller
	{
		public ActionResult Index()
		{
			return View("~/Views/ConvertNumber/ConvertNumber.cshtml");
		}		

		[HttpPost]
		public ActionResult ConvertNumber(MyDetails details)
		{
			string query = "?name=" + details.Name + "&amount=" + details.Amount;
			string url = "http://localhost:59293/api/Values" + query;
			WebClient client = new WebClient();

			string postData = "anything";
			client.Headers.Add("Content-Type", "application/x-www-form-urlencoded");
			// Upload the input string using the HTTP POST method.
			byte[] byteArray = System.Text.Encoding.ASCII.GetBytes(postData);
			byte[] byteResult = client.UploadData(url, "POST", byteArray);
			// Decode and display the result.
			var result = Encoding.ASCII.GetString(byteResult);
			ConversionResponse response = new ConversionResponse
			{
				Amount = result,
				Name = details.Name
			};
			return View("~/Views/ConvertNumber/ConvertNumber.cshtml", response);
		}

	}
}

NumberToTextConversionApplication/NumberToTextConversionApplication/Views/ConvertNumber/ConvertNumber.cshtml
@model NumberToTextConversionApplication.Models.ConversionResponse
@{
    ViewBag.Title = "Conversion Page";
}
<form action="/Convert/ConvertNumber" method="post" style="padding-top: 20px;">
    <label>Enter Name</label>
    <input type="text" name="name" value="" />
    <label>Enter amount</label>
    <input type="text" name="amount" value="" />
    <input type="submit" name="submit" value="SUBMIT" />
</form>
<div class="convert">

    @if (Model != null)
    {
        <h1>Conversion result</h1>
        <h3>Hello @Model.Name</h3>
        <h4>@Model.Amount.TrimEnd().TrimStart()</h4>
    }

</div>

NumberToTextConversionApplication/NumberToTextConversionApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Convert", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Convert", "Index", "Convert")</li>                  
                </ul>        
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>